### ISSUE TITLE
0.3.1 - Susano doesn't work on the server

### ISSUE THREAD

**Issue by Azimkin** [AHZNB/naruto_mod#22]
Susano can't spawn
Error:
[19:46:47] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.util.List
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_312]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_312]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:840) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.util.List
	at net.narutomod.entity.EntitySusanooBase.func_184200_o(EntitySusanooBase.java:267) ~[EntitySusanooBase.class:1.0]
	at net.minecraft.entity.Entity.func_184205_a(Entity.java:2284) ~[vg.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_184205_a(EntityPlayerMP.java:967) ~[oq.class:?]
	at net.minecraft.entity.Entity.func_184220_m(Entity.java:2262) ~[vg.class:?]
	at net.narutomod.entity.EntitySusanooBase.<init>(EntitySusanooBase.java:96) ~[EntitySusanooBase.class:1.0]
	at net.narutomod.entity.EntitySusanooSkeleton$EntityCustom.<init>(EntitySusanooSkeleton.java:61) ~[EntitySusanooSkeleton$EntityCustom.class:1.0]
	at net.narutomod.entity.EntitySusanooSkeleton$EntityCustom.<init>(EntitySusanooSkeleton.java:57) ~[EntitySusanooSkeleton$EntityCustom.class:1.0]
	at net.narutomod.procedure.ProcedureSusanoo.execute(ProcedureSusanoo.java:65) ~[ProcedureSusanoo.class:1.0]
	at net.narutomod.procedure.ProcedureSusanoo.executeProcedure(ProcedureSusanoo.java:121) ~[ProcedureSusanoo.class:1.0]
	at net.decentstudio.narutoaddon.hooklib.hooks.HookProcedureSpecialJutsu2OnKeyPressed.executeProcedure(HookProcedureSpecialJutsu2OnKeyPressed.java:168) ~[HookProcedureSpecialJutsu2OnKeyPressed.class:1.0]
	at net.narutomod.procedure.ProcedureSpecialJutsu2OnKeyPressed.executeProcedure(ProcedureSpecialJutsu2OnKeyPressed.java) ~[ProcedureSpecialJutsu2OnKeyPressed.class:1.0]

	at net.narutomod.keybind.KeyBindingSpecialJutsu2.pressAction(KeyBindingSpecialJutsu2.java:137) ~[KeyBindingSpecialJutsu2.class:1.0]
	at net.narutomod.keybind.KeyBindingSpecialJutsu2.access$000(KeyBindingSpecialJutsu2.java:32) ~[KeyBindingSpecialJutsu2.class:1.0]
	at net.narutomod.keybind.KeyBindingSpecialJutsu2$KeyBindingPressedMessageHandler.lambda$onMessage$0(KeyBindingSpecialJutsu2.java:97) ~[KeyBindingSpecialJutsu2$KeyBindingPressedMessageHandler.class:1.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_312]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_312]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
	
Full log:
[latest(1).log](https://github.com/user-attachments/files/17351295/latest.1.log)

**Comment by Rb4nl** [comment]
Remove the sharingan addon and try again, i can see the ID on your log.

**Comment by AHZNB** [comment]
fixed

**Comment by AHZNB** [comment]
fixed
